* KFoldCV
Our KFoldCV function is located on line 26 of:
https://github.com/sambashiva-sk2292/KFoldCV/main.py
** 1. Environment setup
These steps assume a linux system.
*** 1.1. First clone the repo 
git clone https://github.com/sambashiva-sk2292/KFoldCV/
*** 1.2. Create an arbitrary directory
#+BEGIN_SRC
mkdir ./.venv
#+END_SRC
*** 1.3. Create a virtual environment
#+BEGIN_SRC
python3 -m venv ./.venv
#+END_SRC
*** 1.4. Activate the virtual environment
#+BEGIN_SRC
. ./.venv/bin/activate
#+END_SRC
**** 1.4.1 You can use an easy to remember bash alias to activate the venv
***** 1.4.1.1 Open your ~/.bashrc
#+BEGIN_SRC
vim ~/.bashrc
#+END_SRC
***** 1.4.1.2 Add this line to your ~/.bashrc
#+BEGIN_SRC
alias act=". ./.venv/bin/activate"
#+END_SRC
You can replace act with any valid bash identifier you want.
***** 1.4.1.3 Now reload your ~/.bashrc
#+BEGIN_SRC
source ~/.bashrc
#+END_SRC
***** 1.4.1.4 Now you can use the "act" command
#+BEGIN_SRC
act
#+END_SRC
This will be saved on all future shells sessions for your current user.
*** 1.5. Install module requirements
#+BEGIN_SRC
pip3 install -r ./requirements.txt
#+END_SRC
** 2. Execution
#+BEGIN_SRC
python3 main.py <num-folds> <max-neighbors> <seed>
#+END_SRC
num-folds must be a float
max-neighbors must be an int
seed must be an int
** 3. Reproduce our results
#+BEGIN_SRC
python3 main.py 5 20 3
#+END_SRC
Our 5 figures included in the report will be generated in the current working
directory.
